name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t preet1810/emailshedulebe .
      - name: Tag docker image
        run: docker tag preet1810/emailshedulebe:latest ${{ secrets.DOCKER_USERNAME }}/emailshedulebe:latest
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/emailshedulebe:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Run as root
        run: sudo su
      - name: Pull image from docker hub
        run: docker pull preet1810/emailshedulebe:latest
      - name: Delete old container
        run: docker rm -f emailshedulebe-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name emailshedulebe-container preet1810/emailshedulebe